### ISSUE TITLE
Scope.clear() method by default does nothing

### ISSUE THREAD

**Issue by emmaguy** [memoizr/shank#6] opened 2016-09-16 16:42 UTC
This is very misleading!

Suggest it does the same as `clearWithFinalAction`, but then not have the callback. This is what I expected from the name! But actually all it does is execute an action which is a member, which defaults to nothing

**Comment by memoizr** [comment] 2016-09-16 17:33
I'm not sure I completely understand what you mean by that, here's the way I see it:

`Scope.clear()` will remove the scope from the cache, provided the scope has been used already to obtain a scoped dependency. In case the scope has not been used before, the scope can still be cleared safely, although nothing will happen, as nothing should happen in that case (no objects are kept in the cache for that scope). This allows for having lazy dependencies which may or may not be claimed during the lifetime of the scope. The fact that the scope can be cleared safely means the user doesn't have to think about the internal state of the cache when they perform the clearing action.

So, you create a scope:

```
Scope mScope = Scope.scope(UserActivity.class)
```

and without ever claiming a dependency for that scope, you clear it:

```
mScope.clear() // does nothing, but safe to call;
```

But if you do claim an object using the scope

```
Shank.with(mScope).provideSingleton(UserPresenter.class);
mScope.clear()
```

this time it will clear the scope. Next time you try and get a dependency with the (logically) same scope you won't get the same instance of the object you've asked for, but a new one.

There are some tests that cover the clearing behaviour, maybe they're helpful:
https://github.com/memoizr/shank/blob/master/src/test/java/com.memoizrlabs/ShankAcceptanceTest.java#L863

The package private action (which by default is a no-op) is set internally by the framework as soon as the scope is used to claim a dependency. Here's where that action happens.
https://github.com/memoizr/shank/blob/master/src/main/java/com/memoizrlabs/ScopedCache.java#L28

Note that this is a different thing from the action you pass to `clearWithFinalAction` as that is simply a callback that gives you an opportunity to "say goodbye" to every object in the scope before it gets elected for garbage collection. This is useful for doing some kind of tear-down logic, like killing off some long-running RX subscriptions, for example. In any case, `clearWithFinalAction` will call the normal `clear` method after it's done with the callbacks.

Is this helpful or did you have something else in mind?

**Comment by emmaguy** [comment] 2016-09-17 12:09
So to be clear, I'm talking about this: https://github.com/memoizr/shank/blob/master/src/main/java/com/memoizrlabs/Scope.java#L38

The java doc states `Clears cache for the scope.` but by default it does not!

**Comment by memoizr** [comment] 2016-09-17 18:22
Actually it does clear the scope by default if there's anything that's been bound to it. It doesn't do anything only when there isn't anything to be cleared. If the scope is never used, then the default action is a no-op, because there's just nothing that's associated to the scope. 

Do you have a particular use case in which this is being problematic?

**Comment by emmaguy** [comment] 2016-09-17 20:33
We've seen flakiness in our espresso tests because Shank is not clearing
out old instances, and the next tests are hitting old state 🙁

**Comment by memoizr** [comment] 2016-09-18 08:52
Interesting, could you please post a minimal reproduction of this issue? It might be a bigger issue actually.

**Comment by emmaguy** [comment] 2016-09-21 08:48
I will try to get to this, but it probably will not be soon

**Comment by memoizr** [comment] 2016-10-03 11:11
Closing this as I assume #9 was intended to cover this.

**Closed as completed by memoizr** 2016-10-03 11:11 UTC
